algorithm_description: example DPS algorithm that produces STAC metadata from a COG
algorithm_name: dps-stac-from-cog
algorithm_version: main
build_command: example-dps-stac-from-cog/build.sh
disk_space: 1GB
docker_container_url: mas.maap-project.org/root/maap-workspaces/base_images/vanilla:v3.1.1
inputs:
  config: []
  file: []
  positional:
  - default: ''
    description: Full s3 path (starting with s3://) to the COG file you wish to catalog. Must be a COG and must
    be accessible by the DPS runner. 
    name: s3_path
    required: true
queue: maap-dps-worker-32gb
repository_url: https://github.com/MAAP-Project/example-dps-stac-from-cog.git
run_command: example-dps-stac-from-cog/run.sh
