identifier: "Sentinel 2 L2A True Color Image COG"
algo_id: "dps-stac-from-cog"
version: "main"
username: "emileten"
queue: "maap-dps-worker-32gb"
s3_path: "s3://sentinel-cogs/sentinel-s2-l2a-cogs/51/U/WR/2023/12/S2A_51UWR_20231207_0_L2A/TCI.tif"
